// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformDemo.Core;

#nullable disable

namespace PlatformDemo.Core.Migrations
{
    [DbContext(typeof(PlatformDemoDbContext))]
    partial class PlatformDemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlatformDemo.Core.Model.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8fd65b94-2805-41d5-94e1-6403174b20ce"),
                            Name = "John Smith",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = new Guid("41b1e9a6-d20b-489d-974a-7d005bf7f4a8"),
                            Name = "Emily Johnson",
                            PhoneNumber = "123-456-7891"
                        },
                        new
                        {
                            Id = new Guid("386bc9f2-f6f6-484c-8c3b-2ed671b99ef4"),
                            Name = "Michael Brown",
                            PhoneNumber = "123-456-7892"
                        },
                        new
                        {
                            Id = new Guid("b399e175-0b33-438e-9c08-b4fa4a2e5c59"),
                            Name = "Sophia Williams",
                            PhoneNumber = "123-456-7893"
                        },
                        new
                        {
                            Id = new Guid("976aad69-027e-4112-974b-5d37385e458d"),
                            Name = "Matthew Jones",
                            PhoneNumber = "123-456-7894"
                        },
                        new
                        {
                            Id = new Guid("3a6e36b4-70eb-4c78-99e6-2bb54fffe191"),
                            Name = "Olivia Davis",
                            PhoneNumber = "123-456-7895"
                        },
                        new
                        {
                            Id = new Guid("3c591b9d-ddfa-471d-b653-e4dfeedd51d7"),
                            Name = "Liam Garcia",
                            PhoneNumber = "123-456-7896"
                        },
                        new
                        {
                            Id = new Guid("0440a7c3-d4d4-4e61-a429-d77f88e1baaf"),
                            Name = "Isabella Rodriguez",
                            PhoneNumber = "123-456-7897"
                        },
                        new
                        {
                            Id = new Guid("a114403b-629f-4b69-b1dd-cab3308875bc"),
                            Name = "Lucas Martinez",
                            PhoneNumber = "123-456-7898"
                        },
                        new
                        {
                            Id = new Guid("2c5fe80d-e82d-4f00-9c9d-34fa5d02a5ec"),
                            Name = "Ava Hernandez",
                            PhoneNumber = "123-456-7899"
                        },
                        new
                        {
                            Id = new Guid("95075645-37c2-401f-a879-c5e223a0447b"),
                            Name = "Sebastian Kim",
                            PhoneNumber = "123-456-7800"
                        },
                        new
                        {
                            Id = new Guid("0a0fe0b9-4ab0-461b-a742-802f1ef4aec6"),
                            Name = "Emma Lee",
                            PhoneNumber = "123-456-7801"
                        },
                        new
                        {
                            Id = new Guid("bbdb6ba4-9e3b-43c6-829f-bb3a2723db92"),
                            Name = "William Clark",
                            PhoneNumber = "123-456-7802"
                        },
                        new
                        {
                            Id = new Guid("57e69e95-0e9f-4727-845f-37e5c0233574"),
                            Name = "Mia Lewis",
                            PhoneNumber = "123-456-7803"
                        },
                        new
                        {
                            Id = new Guid("e760ee67-3140-47c2-8634-946fdf44a873"),
                            Name = "Henry Young",
                            PhoneNumber = "123-456-7804"
                        });
                });

            modelBuilder.Entity("PlatformDemo.Core.Model.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderNumber"));

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b705da3e-bc99-4230-84ea-7d5e4b1bae6e"),
                            Amount = 100.50m,
                            CustomerId = new Guid("8fd65b94-2805-41d5-94e1-6403174b20ce"),
                            OrderNumber = 1
                        },
                        new
                        {
                            Id = new Guid("bd24708a-8dd3-4e58-92f0-24e5112f8cd4"),
                            Amount = 200.50m,
                            CustomerId = new Guid("8fd65b94-2805-41d5-94e1-6403174b20ce"),
                            OrderNumber = 2
                        },
                        new
                        {
                            Id = new Guid("43066a60-68e4-4ac9-b8f3-7a55e48549c1"),
                            Amount = 100.50m,
                            CustomerId = new Guid("41b1e9a6-d20b-489d-974a-7d005bf7f4a8"),
                            OrderNumber = 3
                        },
                        new
                        {
                            Id = new Guid("c9aec803-36c3-465a-bbf4-5b3c098dcff8"),
                            Amount = 200.50m,
                            CustomerId = new Guid("41b1e9a6-d20b-489d-974a-7d005bf7f4a8"),
                            OrderNumber = 4
                        },
                        new
                        {
                            Id = new Guid("ae2aa7de-47f3-4fac-ac78-2d2252bc9e3f"),
                            Amount = 100.50m,
                            CustomerId = new Guid("41b1e9a6-d20b-489d-974a-7d005bf7f4a8"),
                            OrderNumber = 5
                        },
                        new
                        {
                            Id = new Guid("e08fad3b-a9af-40dd-ad0a-4045f1b85e70"),
                            Amount = 200.50m,
                            CustomerId = new Guid("41b1e9a6-d20b-489d-974a-7d005bf7f4a8"),
                            OrderNumber = 6
                        },
                        new
                        {
                            Id = new Guid("993fe5bd-cd1e-4794-ba9f-8f28e23056cc"),
                            Amount = 200.50m,
                            CustomerId = new Guid("386bc9f2-f6f6-484c-8c3b-2ed671b99ef4"),
                            OrderNumber = 7
                        },
                        new
                        {
                            Id = new Guid("7d278dad-b049-48b8-87e5-c5e604130b2d"),
                            Amount = 100.50m,
                            CustomerId = new Guid("386bc9f2-f6f6-484c-8c3b-2ed671b99ef4"),
                            OrderNumber = 8
                        },
                        new
                        {
                            Id = new Guid("04de6182-c351-460c-9760-43e077a7f31d"),
                            Amount = 200.50m,
                            CustomerId = new Guid("386bc9f2-f6f6-484c-8c3b-2ed671b99ef4"),
                            OrderNumber = 9
                        },
                        new
                        {
                            Id = new Guid("7f66b17e-a23d-4848-ba90-9d174261368a"),
                            Amount = 100.50m,
                            CustomerId = new Guid("976aad69-027e-4112-974b-5d37385e458d"),
                            OrderNumber = 10
                        },
                        new
                        {
                            Id = new Guid("5ce02d9c-0309-423a-ba1d-4a4afb7c6543"),
                            Amount = 200.50m,
                            CustomerId = new Guid("976aad69-027e-4112-974b-5d37385e458d"),
                            OrderNumber = 11
                        },
                        new
                        {
                            Id = new Guid("f0e053cf-b43b-4cc1-93e9-5edfa834ffb2"),
                            Amount = 200.50m,
                            CustomerId = new Guid("3a6e36b4-70eb-4c78-99e6-2bb54fffe191"),
                            OrderNumber = 12
                        },
                        new
                        {
                            Id = new Guid("9b91223d-0b9a-4ecf-acf6-f6959a43bfa1"),
                            Amount = 200.50m,
                            CustomerId = new Guid("3c591b9d-ddfa-471d-b653-e4dfeedd51d7"),
                            OrderNumber = 13
                        },
                        new
                        {
                            Id = new Guid("514bca15-7964-4bf6-85be-57f43796be31"),
                            Amount = 100.50m,
                            CustomerId = new Guid("3c591b9d-ddfa-471d-b653-e4dfeedd51d7"),
                            OrderNumber = 14
                        },
                        new
                        {
                            Id = new Guid("40db7b6d-7bd1-43c6-9e6e-e8d168bfff8f"),
                            Amount = 200.50m,
                            CustomerId = new Guid("3c591b9d-ddfa-471d-b653-e4dfeedd51d7"),
                            OrderNumber = 15
                        },
                        new
                        {
                            Id = new Guid("33543d58-9e6f-40bb-a85e-74aa7c8eb9cb"),
                            Amount = 200.50m,
                            CustomerId = new Guid("0440a7c3-d4d4-4e61-a429-d77f88e1baaf"),
                            OrderNumber = 16
                        },
                        new
                        {
                            Id = new Guid("0ccb12cc-e43c-4c3b-b334-ed3360bf74e8"),
                            Amount = 100.50m,
                            CustomerId = new Guid("0440a7c3-d4d4-4e61-a429-d77f88e1baaf"),
                            OrderNumber = 17
                        },
                        new
                        {
                            Id = new Guid("b40f6572-1915-4ac6-81b4-2e2983f6b6b0"),
                            Amount = 200.50m,
                            CustomerId = new Guid("0440a7c3-d4d4-4e61-a429-d77f88e1baaf"),
                            OrderNumber = 18
                        },
                        new
                        {
                            Id = new Guid("01f08be3-d92f-4dcc-8b8a-b376a9486573"),
                            Amount = 100.50m,
                            CustomerId = new Guid("a114403b-629f-4b69-b1dd-cab3308875bc"),
                            OrderNumber = 19
                        },
                        new
                        {
                            Id = new Guid("cb5add99-075f-4d82-b684-0e15232ddc2f"),
                            Amount = 200.50m,
                            CustomerId = new Guid("a114403b-629f-4b69-b1dd-cab3308875bc"),
                            OrderNumber = 20
                        },
                        new
                        {
                            Id = new Guid("343154f4-26fc-4a1a-b647-cb7677c7e974"),
                            Amount = 100.50m,
                            CustomerId = new Guid("a114403b-629f-4b69-b1dd-cab3308875bc"),
                            OrderNumber = 21
                        },
                        new
                        {
                            Id = new Guid("d651559f-adc6-4097-aaf6-652fa2b47f5e"),
                            Amount = 200.50m,
                            CustomerId = new Guid("a114403b-629f-4b69-b1dd-cab3308875bc"),
                            OrderNumber = 22
                        },
                        new
                        {
                            Id = new Guid("8c8f3c28-ba21-46e8-af60-dbbf0faaa8ca"),
                            Amount = 200.50m,
                            CustomerId = new Guid("a114403b-629f-4b69-b1dd-cab3308875bc"),
                            OrderNumber = 23
                        },
                        new
                        {
                            Id = new Guid("c35deeb7-dbc1-4adc-8eb9-57e11015d13f"),
                            Amount = 200.50m,
                            CustomerId = new Guid("2c5fe80d-e82d-4f00-9c9d-34fa5d02a5ec"),
                            OrderNumber = 25
                        },
                        new
                        {
                            Id = new Guid("e62af2e6-f3e6-42a5-a020-7fdf1fdb0bc8"),
                            Amount = 200.50m,
                            CustomerId = new Guid("95075645-37c2-401f-a879-c5e223a0447b"),
                            OrderNumber = 26
                        },
                        new
                        {
                            Id = new Guid("3afc0387-1d03-43a1-b9c8-eb757011c68d"),
                            Amount = 200.50m,
                            CustomerId = new Guid("0a0fe0b9-4ab0-461b-a742-802f1ef4aec6"),
                            OrderNumber = 27
                        },
                        new
                        {
                            Id = new Guid("45637736-2e95-4859-9a24-d0e77adc26f5"),
                            Amount = 200.50m,
                            CustomerId = new Guid("0a0fe0b9-4ab0-461b-a742-802f1ef4aec6"),
                            OrderNumber = 28
                        },
                        new
                        {
                            Id = new Guid("9ed6bcac-a364-4724-838b-14c99017b64e"),
                            Amount = 200.50m,
                            CustomerId = new Guid("bbdb6ba4-9e3b-43c6-829f-bb3a2723db92"),
                            OrderNumber = 29
                        },
                        new
                        {
                            Id = new Guid("20b8a648-ccf4-4726-8579-47b2deac0aaa"),
                            Amount = 200.50m,
                            CustomerId = new Guid("bbdb6ba4-9e3b-43c6-829f-bb3a2723db92"),
                            OrderNumber = 30
                        },
                        new
                        {
                            Id = new Guid("49c29393-1b1b-41f2-8735-e3039322c93f"),
                            Amount = 200.50m,
                            CustomerId = new Guid("57e69e95-0e9f-4727-845f-37e5c0233574"),
                            OrderNumber = 31
                        },
                        new
                        {
                            Id = new Guid("1dfbf4ff-c3d4-44f4-a21d-d85d754ecea0"),
                            Amount = 100.50m,
                            CustomerId = new Guid("57e69e95-0e9f-4727-845f-37e5c0233574"),
                            OrderNumber = 32
                        },
                        new
                        {
                            Id = new Guid("b71694f2-5dae-4af1-ae50-96702f5dce99"),
                            Amount = 200.50m,
                            CustomerId = new Guid("57e69e95-0e9f-4727-845f-37e5c0233574"),
                            OrderNumber = 33
                        });
                });

            modelBuilder.Entity("PlatformDemo.Core.Model.Order", b =>
                {
                    b.HasOne("PlatformDemo.Core.Model.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PlatformDemo.Core.Model.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
